# Generated by Django 4.2.7 on 2023-11-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Items',
            new_name='Order_Item',
        ),
    ]
