# Generated by Django 4.2.7 on 2023-11-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_order_items_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
